### ISSUE TITLE
When city is not determined, answer contans 'True' instead of name

### ISSUE THREAD

**Issue by M1hacka** [idlesign/pysyge#12]
Hi.
When city is not determined from database (sypex online tester returns only country) I get `True` instead of city and region names:
http://prntscr.com/q73qb8
```python
geo_obj.get_location('91.210.107.80', detailed=True)
```
```json
{"country_id": 185, "country_iso": "RU", "region_id": 0, "city": true, "lon": 100.0, "lat": 60.0, "fips": "0", "info": {"city": {"id": 0, "lat": 60.0, "lon": 100.0, "name_ru": true, "name_en": true}, "region": {"id": 0, "name_ru": true, "name_en": true, "iso": true}, "country": {"id": 185, "iso": "RU", "lat": 60.0, "lon": 100.0, "name_ru": "Россия", "name_en": "Russia"}}, "region": true, "tz": ""}
```

**Comment by idlesign** [comment]
Hi. Thank you for the report.
We'll need to consult the reference implementation (in PHP) to find out how to handle this according to spec.
I'll try to peep into in a week.

**Comment by idlesign** [comment]
Seems to be fixed in 1.1.0.  Now there are empty strings.
Please try it out.

**Comment by M1hacka** [comment]
Thanks, we'll test it soon

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
