### ISSUE TITLE
This algorithm is incorrect

### ISSUE THREAD

**Issue by Leemurus** [idlesign/pysyge#13]
https://github.com/idlesign/pysyge/blob/3d57522f163edf1fc0df22d4069b0fb2d5bc070f/pysyge/pysyge.py#L186

For example, ipn == str_[start:start + 3], you should increase min_ border, because 'str_[start:start + 3]' is the left border of a new range.

**Comment by idlesign** [comment]
Thank you.
Please provide a minimal case revealing the problem (e.g. IP).

**Comment by Leemurus** [comment]
You can test that on 1.0.74.0 ip. Right answer is 2463930 seek. Because you have min_=13, max_=13, and your formula is  min_ * len_block - len_id, but in this situation ipn == min_ * len_block + len_id

**Comment by idlesign** [comment]
Thank you.
Will fix when have time, or pull request (fix + test) is welcome if you wish.

**Comment by idlesign** [comment]
Unable to reproduce for 1.0.74.0 (see linked quirk test).
Please provide a proper example and reopen if required.
