### ISSUE TITLE
Periodically, I get an error on the site

### ISSUE THREAD

**Issue by ademaro** [idlesign/pysyge#15]
Hello. 
I can't understand - an error occurs periodically, help me figure it out.

```log
  File "/var/www/.venvs/python38/lib/python3.8/site-packages/pysyge/pysyge.py", line 446, in get_location
    return self._parse_location(seek, detailed=detailed)
  File "/var/www/.venvs/python38/lib/python3.8/site-packages/pysyge/pysyge.py", line 308, in _parse_location
    city = self._read_data_chunk(self._TYPE_CITY, start_pos, self._max_city)
  File "/var/www/.venvs/python38/lib/python3.8/site-packages/pysyge/pysyge.py", line 291, in _read_data_chunk
    return self._parse_pack(self._pack[data_type], raw)
  File "/var/www/.venvs/python38/lib/python3.8/site-packages/pysyge/pysyge.py", line 417, in _parse_pack
    val_real = val_real.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
```

What can be and where to look for details? Thanks!)

**Comment by idlesign** [comment]
Hi,

To reproduce and envestigate it'll require DB version you use and bogus IP address(es).

**Comment by ademaro** [comment]
ip: `109.207.230.244`
db (SxGeoCity.dat):
```
>>> print('DB version %s (%s)' % (geodata.get_db_version(), geodata.get_db_date()))
DB version 22 (2020-12-28 21:16:41)
```

**Comment by ademaro** [comment]
There was some kind of glitch and a lot of errors that day:
https://i.imgur.com/VLR7ECX.png

I took the IP address from the web server logs, they could be incorrectly identified in the application ..
errors start from here: `geodata.get_location (ip, detailed = True)`

my python version:
```
Python 3.8.2 (default, Apr  1 2020, 15:52:55)
[GCC 9.3.0] on linux
```

Errors are no longer at the moment, so I think it is related somehow to the server was (big load was and resources might not be enough). Therefore, you can close the ticket, there will be details — I will write it down.

**Comment by idlesign** [comment]
You may want to try to generate a load with Yandex.Tank or similar, and also to play with .dat file open modes (batch, memory, file).

> Therefore, you can close the ticket, there will be details — I will write it down.

Agreed. Feel free to reopen if required.
