### ISSUE TITLE
generates an exception when an IP address is not in the database

### ISSUE THREAD

**Issue by PyNew** [idlesign/pysyge#6]
generates an exception like

**TypeError: 'bool' object has no attribute '__ __getitem__ __'**

For example: type into  https://sypexgeo.net/ru/demo/ list of IP's

163.53.186.51
185.26.183.14
185.26.183.14
45.64.99.151
104.235.29.75
104.236.81.126
104.41.151.86
154.72.48.97
45.63.53.242
104.238.83.28
103.230.136.250

![sypexgeo](https://cloud.githubusercontent.com/assets/13621711/9034494/c251e300-39d8-11e5-89d0-50a1e20743f9.PNG)

### solution:

instead

    location = geodata.get_location(proxy.strip().split(':')[0], detailed=False)
    iso = location['country_iso']

use

    try:
        location = geodata.get_location(proxy.strip().split(':')[0], detailed=False)
        iso = location['country_iso']
    except:
        iso = 'UNKNOWN'
        pass

**Comment by idlesign** [comment]
If location is `None` that with high probability indicates IP database format mismatch (see #5).
Closing this one as a duplicate.
